[package]
name = "cirno"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["derive"] }
crossterm = "0.27.0"
logos = "0.13.0"
thiserror = "1.0.49"
